# Generated by Django 4.0.6 on 2022-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/profile/%Y/%m/%d/', verbose_name='Фото профиля'),
        ),
    ]
